# Script para corregir caracteres corruptos en páginas
# Reemplaza caracteres corruptos por sus equivalentes correctos

$pagesDir = "c:\Users\conej\Documents\conecta-social-comunidad-main\src\pages"
$files = Get-ChildItem -Path $pagesDir -Filter "*.tsx" -Recurse

$replacements = @{
    # Caracteres corruptos comunes
    "??" = "í"
    "?" = "á"
    "?" = "é"
    "?" = "ó"
    "?" = "ú"
    "?" = "ñ"
    "?" = "Á"
    "?" = "É"
    "?" = "Í"
    "?" = "Ó"
    "?" = "Ú"
    "?" = "Ñ"
    "?" = "ü"
    "?" = "Ü"
    
    # Palabras comunes con caracteres faltantes
    "Gua" = "Guía"
    "prcticas" = "prácticas"
    "Mara" = "María"
    "Gonzlez" = "González"
    "Qu" = "Qué"
    "Cmo" = "Cómo"
    "Autntico" = "Auténtico"
    "Atractivo" = "Atractivo"
    "mximo" = "máximo"
    "exclusiva" = "exclusiva"
    "novedades" = "novedades"
    "Experiencia" = "Experiencia"
    "Social" = "Social"
    "Premium" = "Premium"
    "Verificacin" = "Verificación"
    "Biomtrica" = "Biométrica"
    "Encriptacin" = "Encriptación"
    "Cumplimiento" = "Cumplimiento"
    "Moderacin" = "Moderación"
    "Deteccin" = "Detección"
    "Fraude" = "Fraude"
    "Equipo" = "Equipo"
    "Moderadores" = "Moderadores"
    "Especializados" = "Especializados"
    "Relaciones" = "Relaciones"
    "nete" = "Únete"
    "Estadsticas" = "Estadísticas"
    "Logros" = "Logros"
    "Nmeros" = "Números"
    "Versin" = "Versión"
    "Actual" = "Actual"
    "Tablas" = "Tablas"
    "Base" = "Base"
    "Datos" = "Datos"
    "Tests" = "Tests"
    "Pasando" = "Pasando"
    "Nativo" = "Nativo"
    "Seguridad" = "Seguridad"
    "Privacidad" = "Privacidad"
    "Compromiso" = "Compromiso"
    "AES-GCM" = "AES-GCM"
    "Grado" = "Grado"
    "Empresarial" = "Empresarial"
    "Protegidos" = "Protegidos"
    "Cifrado" = "Cifrado"
    "Militar" = "Militar"
    "Certificados" = "Certificados"
    "Proteccin" = "Protección"
    "Europea" = "Europea"
    "Mexicana" = "Mexicana"
    "Hbrido" = "Híbrido"
    "Documento" = "Documento"
    "Oficial" = "Oficial"
    "Selfie" = "Selfie"
    "Telefnica" = "Telefónica"
    "Avanzada" = "Avanzada"
    "Identificar" = "Identificar"
    "Perfiles" = "Perfiles"
    "Falsos" = "Falsos"
    "Comportamiento" = "Comportamiento"
    "Sospechoso" = "Sospechoso"
    "Humanos" = "Humanos"
    "Lifestyle" = "Lifestyle"
    "Listo" = "Listo"
    "Conectar" = "Conectar"
    "Creciente" = "Creciente"
    "Comunidad" = "Comunidad"
    "Construyendo" = "Construyendo"
    "Especial" = "Especial"
    "Juntos" = "Juntos"
    "Crear" = "Crear"
    "Cuenta" = "Cuenta"
    "Gratis" = "Gratis"
    "Contactar" = "Contactar"
    "Soporte" = "Soporte"
    "Misin" = "Misión"
    "Visin" = "Visión"
    "Valores" = "Valores"
    "Nuestros" = "Nuestros"
    "Espacio" = "Espacio"
    "Seguro" = "Seguro"
    "Parejas" = "Parejas"
    "Solteros" = "Solteros"
    "Conectar" = "Conectar"
    "Manera" = "Manera"
    "Autntica" = "Auténtica"
    "Explorando" = "Explorando"
    "Nuevas" = "Nuevas"
    "Experiencias" = "Experiencias"
    "Total" = "Total"
    "Discrecin" = "Discreción"
    "Respeto" = "Respeto"
    "Mutuo" = "Mutuo"
    "Convertirnos" = "Convertirnos"
    "Plataforma" = "Plataforma"
    "Confiable" = "Confiable"
    "Reconocida" = "Reconocida"
    "Brindar" = "Brindar"
    "Ambiente" = "Ambiente"
    "Tecnologa" = "Tecnología"
    "Moderna" = "Moderna"
    "Compromiso" = "Compromiso"
    "Usuarios" = "Usuarios"
    "Sistema" = "Sistema"
    "Verificacin" = "Verificación"
    "Usuarios" = "Usuarios"
    "Datos" = "Datos"
    "Personales" = "Personales"
    "Cdigos" = "Códigos"
    "tica" = "Ética"
    "Bien" = "Bien"
    "Definidos" = "Definidos"
    "Algoritmo" = "Algoritmo"
    "Avanzado" = "Avanzado"
    "Segn" = "Según"
    "Compatibilidad" = "Compatibilidad"
    "Preferencias" = "Preferencias"
    "Autenticacin" = "Autenticación"
    "Facial" = "Facial"
    "Huella" = "Huella"
    "Digital" = "Digital"
    "Mintados" = "Mintados"
    "Tokens" = "Tokens"
    "Deteccin" = "Detección"
    "Consentimiento" = "Consentimiento"
    "Chats" = "Chats"
    "Graphs" = "Graphs"
    "Conexiones" = "Conexiones"
    "Friends" = "Friends"
    "Emocionales" = "Emocionales"
    "Eventos" = "Eventos"
    "Virtuales" = "Virtuales"
    "Sostenibles" = "Sostenibles"
    "Recompensas" = "Recompensas"
    "CMPX" = "CMPX"
    "Historias" = "Historias"
    "Efmeras" = "Efímeras"
    "Comparte" = "Comparte"
    "Momentos" = "Momentos"
    "Desaparecen" = "Desaparecen"
    "Horas" = "Horas"
    "Galeras" = "Galerías"
    "NFT" = "NFT"
    "Verificadas" = "Verificadas"
    "Mintados" = "Mintados"
    "GTK" = "GTK"
    "Verificador" = "Verificador"
    "Predictivo" = "Predictivo"
}

Write-Host "🔧 Iniciando corrección de caracteres corruptos..." -ForegroundColor Cyan
$fixedCount = 0

foreach ($file in $files) {
    $content = Get-Content -Path $file.FullName -Encoding UTF8 -Raw
    $originalContent = $content
    
    foreach ($key in $replacements.Keys) {
        if ($content -match [regex]::Escape($key)) {
            $content = $content -replace [regex]::Escape($key), $replacements[$key]
            Write-Host "  ✓ Corregido en $($file.Name): '$key' → '$($replacements[$key])'" -ForegroundColor Green
        }
    }
    
    if ($content -ne $originalContent) {
        Set-Content -Path $file.FullName -Value $content -Encoding UTF8
        $fixedCount++
    }
}

Write-Host "✅ Corrección completada: $fixedCount archivos actualizados" -ForegroundColor Green
