CREATE TABLE IF NOT EXISTS club_applications (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  owner_name VARCHAR(255) NOT NULL,
  owner_age INT NOT NULL,
  owner_gender VARCHAR(50) NOT NULL,
  owner_rfc VARCHAR(50) NOT NULL,
  rep_name VARCHAR(255) NOT NULL,
  rep_position VARCHAR(255) NOT NULL,
  rep_phone VARCHAR(50) NOT NULL,
  rep_email VARCHAR(255) NOT NULL,
  club_name VARCHAR(255) NOT NULL,
  address TEXT NOT NULL,
  location VARCHAR(255) NOT NULL,
  state VARCHAR(255) NOT NULL,
  zip_code VARCHAR(50) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  whatsapp VARCHAR(50) NOT NULL,
  website VARCHAR(255),
  use_app_as_website BOOLEAN NOT NULL DEFAULT FALSE,
  email VARCHAR(255) NOT NULL,
  description TEXT,
  club_type VARCHAR(255) NOT NULL,
  hours TEXT NOT NULL,
  capacity INT NOT NULL,
  documents_url VARCHAR(255) NOT NULL,
  company_rfc VARCHAR(50) NOT NULL,
  license VARCHAR(255) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  temp_password VARCHAR(255) NOT NULL,
  temp_password_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  temp_password_used BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT chk_club_application_status CHECK (status IN ('pending', 'approved', 'rejected'))
);

