export const explicitInterests = [
  "Swinger",
  "Parejas",
  "Intercambio",
  "Liberal",
  "Soft Swap",
  "Hard Swap",
  "Clubs Exclusivos",
  "Eventos VIP",
  "Fiestas Privadas",
  "Tantra",
  "BDSM",
  "Poliamor",
  "Cuckolding",
  "Hotwife",
  "Lifestyle Swinger",
] as const;
