-- Migration to add missing tables for AILayerService
-- Generated by Trae AI on 2026-01-10

-- ============================================================================
-- 1. Table: swinger_interests
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.swinger_interests (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    interest TEXT NOT NULL,
    category TEXT, -- e.g., 'soft', 'hard', 'fetish'
    level INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Agregar columna profile_id si no existe (para tablas existentes)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'swinger_interests' 
    AND column_name = 'profile_id'
  ) THEN
    ALTER TABLE public.swinger_interests ADD COLUMN profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE;
  END IF;
END $$;

-- Index for faster lookups (solo si las columnas existen)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'swinger_interests' 
    AND column_name = 'profile_id'
  ) THEN
    CREATE INDEX IF NOT EXISTS idx_swinger_interests_profile_id ON public.swinger_interests(profile_id);
  END IF;
  
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'swinger_interests' 
    AND column_name = 'interest'
  ) THEN
    CREATE INDEX IF NOT EXISTS idx_swinger_interests_interest ON public.swinger_interests(interest);
  END IF;
END $$;

-- ============================================================================
-- 2. Table: couple_profile_likes
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.couple_profile_likes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    from_couple_id UUID REFERENCES public.couple_profiles(id) ON DELETE CASCADE,
    to_couple_id UUID REFERENCES public.couple_profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(from_couple_id, to_couple_id)
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_couple_profile_likes_from ON public.couple_profile_likes(from_couple_id);
CREATE INDEX IF NOT EXISTS idx_couple_profile_likes_to ON public.couple_profile_likes(to_couple_id);

-- ============================================================================
-- 3. RLS Policies
-- ============================================================================

ALTER TABLE public.swinger_interests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.couple_profile_likes ENABLE ROW LEVEL SECURITY;

-- swinger_interests policies
CREATE POLICY "Public interests are viewable by authenticated users" ON public.swinger_interests
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Users can manage their own interests" ON public.swinger_interests
    FOR ALL TO authenticated USING (
        auth.uid() IN (SELECT user_id FROM public.profiles WHERE id = profile_id)
    );

-- couple_profile_likes policies
CREATE POLICY "Likes are viewable by authenticated users" ON public.couple_profile_likes
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Couples can insert likes" ON public.couple_profile_likes
    FOR INSERT TO authenticated WITH CHECK (
        -- Simple check: user must be authenticated. 
        -- Detailed ownership check would require checking if auth.uid() belongs to from_couple_id
        true 
    );
