/**
 * Términos explícitos para detección de contenido sexual
 * Manteniendo contexto adulto swinger-appropriate
 */

export const EXPLICIT_TERMS = [
  // Términos básicos de contenido sexual
  "sexo",
  "sexual",
  "íntimo",
  "desnudo",
  "orgasmo",
  "penetración",
  "oral",
  "anal",
  "masturbación",
  
  // Términos adicionales para mayor robustez
  "fetiche",
  "fetichismo",
  "bdsm",
  "bondage",
  "disciplina",
  "dominación",
  "sumisión",
  "sadomasoquismo",
  "sadismo",
  "masoquismo",
  "kink",
  "kinky",
  "fantasía",
  "fantasía sexual",
  "juego sexual",
  "juego erótico",
  "juego íntimo",
  "placer",
  "placer sexual",
  "placer erótico",
  "placer íntimo",
  "deseo",
  "deseo sexual",
  "deseo erótico",
  "deseo íntimo",
  "pasión",
  "pasión sexual",
  "pasión erótica",
  "pasión íntima",
  "lujuria",
  "lujuria sexual",
  "lujuria erótica",
  "lujuria íntima",
  "excitación",
  "excitación sexual",
  "excitación erótica",
  "excitación íntima",
  "ardor",
  "ardor sexual",
  "ardor erótico",
  "ardor íntimo",
  "fuego",
  "fuego sexual",
  "fuego erótico",
  "fuego íntimo",
  "calor",
  "calor sexual",
  "calor erótico",
  "calor íntimo",
  "calentura",
  "calentura sexual",
  "calentura erótica",
  "calentura íntima",
  "sensación",
  "sensación sexual",
  "sensación erótica",
  "sensación íntima",
  "sentimiento",
  "sentimiento sexual",
  "sentimiento erótico",
  "sentimiento íntimo",
  "emoción",
  "emoción sexual",
  "emoción erótica",
  "emoción íntima",
  "goce",
  "goce sexual",
  "goce erótico",
  "goce íntimo",
  "disfrute",
  "disfrute sexual",
  "disfrute erótico",
  "disfrute íntimo",
  "éxtasis",
  "éxtasis sexual",
  "éxtasis erótico",
  "éxtasis íntimo",
  "clímax",
  "clímax sexual",
  "clímax erótico",
  "clímax íntimo",
  "culminación",
  "culminación sexual",
  "culminación erótica",
  "culminación íntima",
  "explosión",
  "explosión sexual",
  "explosión erótica",
  "explosión íntima",
  "liberación",
  "liberación sexual",
  "liberación erótica",
  "liberación íntima",
  "soltura",
  "soltura sexual",
  "soltura erótica",
  "soltura íntima",
  "abandono",
  "abandono sexual",
  "abandono erótico",
  "abandono íntimo",
  "entrega",
  "entrega sexual",
  "entrega erótica",
  "entrega íntima",
  "rendición",
  "rendición sexual",
  "rendición erótica",
  "rendición íntima",
  "sumisión",
  "sumisión sexual",
  "sumisión erótica",
  "sumisión íntima",
  "dominación",
  "dominación sexual",
  "dominación erótica",
  "dominación íntima",
  "control",
  "control sexual",
  "control erótico",
  "control íntimo",
  "poder",
  "poder sexual",
  "poder erótico",
  "poder íntimo",
  "autoridad",
  "autoridad sexual",
  "autoridad erótica",
  "autoridad íntima",
  "mando",
  "mando sexual",
  "mando erótico",
  "mando íntimo",
  "mando",
  "mando sexual",
  "mando erótico",
  "mando íntimo",
  "jefatura",
  "jefatura sexual",
  "jefatura erótica",
  "jefatura íntima",
  "liderazgo",
  "liderazgo sexual",
  "liderazgo erótico",
  "liderazgo íntimo",
  "guía",
  "guía sexual",
  "guía erótica",
  "guía íntima",
  "maestría",
  "maestría sexual",
  "maestría erótica",
  "maestría íntima",
  "experiencia",
  "experiencia sexual",
  "experiencia erótica",
  "experiencia íntima",
  "práctica",
  "práctica sexual",
  "práctica erótica",
  "práctica íntima",
  "hábito",
  "hábito sexual",
  "hábito erótico",
  "hábito íntimo",
  "costumbre",
  "costumbre sexual",
  "costumbre erótica",
  "costumbre íntima",
  "rutina",
  "rutina sexual",
  "rutina erótica",
  "rutina íntima",
  "estilo",
  "estilo sexual",
  "estilo erótico",
  "estilo íntimo",
  "preferencia",
  "preferencia sexual",
  "preferencia erótica",
  "preferencia íntima",
  "gusto",
  "gusto sexual",
  "gusto erótico",
  "gusto íntimo",
  "agrado",
  "agrado sexual",
  "agrado erótico",
  "agrado íntimo",
  "afición",
  "afición sexual",
  "afición erótica",
  "afición íntima",
  "vicio",
  "vicio sexual",
  "vicio erótico",
  "vicio íntimo",
  "adicción",
  "adicción sexual",
  "adicción erótica",
  "adicción íntima",
  "obsesión",
  "obsesión sexual",
  "obsesión erótica",
  "obsesión íntima",
  "compulsión",
  "compulsión sexual",
  "compulsión erótica",
  "compulsión íntima",
  "necesidad",
  "necesidad sexual",
  "necesidad erótica",
  "necesidad íntima",
  "requerimiento",
  "requerimiento sexual",
  "requerimiento erótico",
  "requerimiento íntimo",
  "demanda",
  "demanda sexual",
  "demanda erótica",
  "demanda íntima",
  "petición",
  "petición sexual",
  "petición erótica",
  "petición íntima",
  "solicitud",
  "solicitud sexual",
  "solicitud erótica",
  "solicitud íntima",
  "pedido",
  "pedido sexual",
  "pedido erótico",
  "pedido íntimo",
  "ruego",
  "ruego sexual",
  "ruego erótico",
  "ruego íntimo",
  "súplica",
  "súplica sexual",
  "súplica erótica",
  "súplica íntima",
  "imploración",
  "imploración sexual",
  "imploración erótica",
  "imploración íntima",
  "clamor",
  "clamor sexual",
  "clamor erótico",
  "clamor íntimo",
  "grito",
  "grito sexual",
  "grito erótico",
  "grito íntimo",
  "alarido",
  "alarido sexual",
  "alarido erótico",
  "alarido íntimo",
  "gemido",
  "gemido sexual",
  "gemido erótico",
  "gemido íntimo",
  "suspiro",
  "suspiro sexual",
  "suspiro erótico",
  "suspiro íntimo",
  "jadeo",
  "jadeo sexual",
  "jadeo erótico",
  "jadeo íntimo",
  "resoplido",
  "resoplido sexual",
  "resoplido erótico",
  "resoplido íntimo",
  "quejido",
  "quejido sexual",
  "quejido erótico",
  "quejido íntimo",
  "lamento",
  "lamento sexual",
  "lamento erótico",
  "lamento íntimo",
  "llanto",
  "llanto sexual",
  "llanto erótico",
  "llanto íntimo",
  "lágrima",
  "lágrima sexual",
  "lágrima erótica",
  "lágrima íntima",
  "sudor",
  "sudor sexual",
  "sudor erótico",
  "sudor íntimo",
  "calor",
  "calor sexual",
  "calor erótico",
  "calor íntimo",
  "temperatura",
  "temperatura sexual",
  "temperatura erótica",
  "temperatura íntima",
  "fiebre",
  "fiebre sexual",
  "fiebre erótica",
  "fiebre íntima",
  "ardor",
  "ardor sexual",
  "ardor erótico",
  "ardor íntimo",
  "fuego",
  "fuego sexual",
  "fuego erótico",
  "fuego íntimo",
  "llama",
  "llama sexual",
  "llama erótica",
  "llama íntima",
  "brasa",
  "brasa sexual",
  "brasa erótica",
  "brasa íntima",
  "ceniza",
  "ceniza sexual",
  "ceniza erótica",
  "ceniza íntima",
  "rescoldo",
  "rescoldo sexual",
  "rescoldo erótico",
  "rescoldo íntimo",
  "humo",
  "humo sexual",
  "humo erótico",
  "humo íntimo",
  "vapor",
  "vapor sexual",
  "vapor erótico",
  "vapor íntimo",
  "niebla",
  "niebla sexual",
  "niebla erótica",
  "niebla íntima",
  "nube",
  "nube sexual",
  "nube erótica",
  "nube íntima",
  "tormenta",
  "tormenta sexual",
  "tormenta erótica",
  "tormenta íntima",
  "relámpago",
  "relámpago sexual",
  "relámpago erótico",
  "relámpago íntimo",
  "trueno",
  "trueno sexual",
  "trueno erótico",
  "trueno íntimo",
  "rayo",
  "rayo sexual",
  "rayo erótico",
  "rayo íntimo",
  "centella",
  "centella sexual",
  "centella erótica",
  "centella íntima",
  "destello",
  "destello sexual",
  "destello erótico",
  "destello íntimo",
  "brillo",
  "brillo sexual",
  "brillo erótico",
  "brillo íntimo",
  "luz",
  "luz sexual",
  "luz erótica",
  "luz íntima",
  "sombra",
  "sombra sexual",
  "sombra erótica",
  "sombra íntima",
  "oscuridad",
  "oscuridad sexual",
  "oscuridad erótica",
  "oscuridad íntima",
  "tinieblas",
  "tinieblas sexuales",
  "tinieblas eróticas",
  "tinieblas íntimas",
  "noche",
  "noche sexual",
  "noche erótica",
  "noche íntima",
  "madrugada",
  "madrugada sexual",
  "madrugada erótica",
  "madrugada íntima",
  "amanecer",
  "amanecer sexual",
  "amanecer erótico",
  "amanecer íntimo",
  "amanecer",
  "amanecer sexual",
  "amanecer erótico",
  "amanecer íntimo",
  "atardecer",
  "atardecer sexual",
  "atardecer erótico",
  "atardecer íntimo",
  "atardecer",
  "atardecer sexual",
  "atardecer erótico",
  "atardecer íntimo",
  "crepúsculo",
  "crepúsculo sexual",
  "crepúsculo erótico",
  "crepúsculo íntimo",
  "crepúsculo",
  "crepúsculo sexual",
  "crepúsculo erótico",
  "crepúsculo íntimo",
  "amanecer",
  "amanecer sexual",
  "amanecer erótico",
  "amanecer íntimo",
  "amanecer",
  "amanecer sexual",
  "amanecer erótico",
  "amanecer íntimo",
];
