/**
 * Lista de palabras prohibidas para moderación de contenido
 * Manteniendo contexto swinger apropiado
 */

export const INAPPROPRIATE_WORDS = new Set([
  // Palabras explícitamente prohibidas (manteniendo contexto swinger apropiado)
  "menor",
  "niño",
  "niña",
  "adolescente",
  "escolar",
  "drogas",
  "cocaína",
  "marihuana",
  "heroína",
  "prostitución",
  "escort",
  "pago",
  "dinero por",
  "violencia",
  "golpear",
  "lastimar",
  "forzar",
  "secuestro",
  "hacker",
  "hacking",
  "abuso",
  "abusar",
  "maltrato",
  "agresión",
  "agredir",
  "asalto",
  "robo",
  "estafa",
  "fraude",
  "extorsión",
  "chantaje",
  "amenaza",
  "amenazar",
  "matar",
  "asesinar",
  "asesinato",
  "homicidio",
  "suicidio",
  "arma",
  "armas",
  "pistola",
  "cuchillo",
  "navaja",
  "bomba",
  "explosivo",
  "terrorismo",
  "pedofilia",
  "pedófilo",
  "abuso sexual",
  "violación",
  "violar",
  "acoso",
  "acosar",
  "hostigamiento",
  "tráfico",
  "tráfico humano",
  "esclavitud",
  "trata de blancas",
  "pornografía infantil",
  "menores de edad",
  "prepuber",
  "prepuberal",
  "infantil",
  "loli",
  "lolita",
  "shota",
  "incesto",
  "bestialidad",
  "zoofilia",
  "necrofilia",
  "cannibalismo",
  "canibalismo",
  "ritual satánico",
  "satanismo",
  "culto",
  "secta",
  "lavado de dinero",
  "blanqueo",
  "narcotráfico",
  "cártel",
  "máfia",
  "pandilla",
  "maras",
  "gang",
  "sicario",
  "matón",
  "asesino a sueldo",
  "contrato",
  "contratado",
  "secuestrar",
  "secuestrador",
  "rescate",
  "cobro de rescate",
  "extorsionar",
  "extorsionista",
  "chantajista",
  "blackmail",
  "pornografía no consensuada",
  "revenge porn",
  "pornografía de venganza",
  "deepfake",
  "revenge porn",
  "doxing",
  "doxear",
  "filtrar datos",
  "filtrar información",
  "hackear cuenta",
  "robar cuenta",
  "suplantar identidad",
  "suplantación",
  "phishing",
  "scam",
  "estafa online",
  "criptomoneda",
  "bitcoin",
  "ethereum",
  "crypto",
  "inversión",
  "invertir",
  "ganar dinero",
  "ganar dinero rápido",
  "dinero fácil",
  "negocio",
  "oportunidad de negocio",
  "mlm",
  "multinivel",
  "pirámide",
  "esquema piramidal",
  "cripto estafa",
  "trading",
  "forex",
  "opciones binarias",
  "apuestas",
  "casino",
  "juegos de azar",
  "apostar",
  "ruleta",
  "blackjack",
  "póker",
  "tragamonedas",
  "slots",
  "apuestas deportivas",
  "bookmaker",
  "casa de apuestas",
  "bono",
  "bono gratis",
  "sin depósito",
  "free spins",
  "giros gratis",
  "jackpot",
  "progresivo",
  "máquina tragamonedas",
  "casino en vivo",
  "live casino",
  "dealer en vivo",
  "crupier",
  "mesa de juego",
  "apostar online",
  "apostar en línea",
  "ganar apostando",
  "ganar jugando",
  "jugar y ganar",
  "jugar por dinero",
  "apuestas reales",
  "dinero real",
  "apostar con dinero",
  "ganar premios",
  "premio en efectivo",
  "cash prize",
  "retirar ganancias",
  "retirar dinero",
  "cobrar ganancias",
  "cobrar dinero",
  "depósito mínimo",
  "mínimo depósito",
  "sin riesgo",
  "sin arriesgar",
  "garantizado",
  "ganancia garantizada",
  "ganar siempre",
  "siempre gana",
  "estrategia ganadora",
  "sistema ganador",
  "método infalible",
  "truco",
  "hack",
  "bot",
  "software",
  "programa",
  "algoritmo",
  "predicción",
  "predecir",
  "analizar",
  "señales",
  "señal",
  "tip",
  "consejo",
  "recomendación",
  "experto",
  "profesional",
  "gurú",
  "mentor",
  "coach",
  "entrenador",
  "academia",
  "curso",
  "clase",
  "taller",
  "seminario",
  "webinar",
  "masterclass",
  "formación",
  "capacitación",
  "aprender",
  "educación",
  "certificado",
  "diploma",
  "título",
  "licencia",
  "credencial",
  "acreditación",
  "certificación",
  "validación",
  "verificación",
  "aprobado",
  "oficial",
  "autorizado",
  "regulado",
  "legal",
  "legítimo",
  "seguro",
  "confiable",
  "confiable",
  "confianza",
  "garantía",
  "garantizado",
  "asegurado",
  "protegido",
  "seguridad",
  "protección",
  "privacidad",
  "datos personales",
  "información personal",
  "información confidencial",
  "datos confidenciales",
  "información sensible",
  "datos sensibles",
  "privado",
  "confidencial",
  "secreto",
  "discreto",
  "anónimo",
  "anónimato",
  "sin rastro",
  "sin dejar rastro",
  "borrar rastros",
  "eliminar rastros",
  "ocultar",
  "ocultar identidad",
  "máscara",
  "disfraz",
  "falso",
  "falsificación",
  "falsificar",
  "documento falso",
  "identidad falsa",
  "nombre falso",
  "alias",
  "seudónimo",
  "nick",
  "nickname",
  "usuario",
  "cuenta",
  "perfil",
  "biografía",
  "bio",
  "descripción",
  "descripción personal",
  "información de contacto",
  "contacto",
  "teléfono",
  "celular",
  "móvil",
  "whatsapp",
  "telegram",
  "instagram",
  "facebook",
  "twitter",
  "tiktok",
  "snapchat",
  "linkedin",
  "correo",
  "email",
  "gmail",
  "hotmail",
  "outlook",
  "yahoo",
  "dirección",
  "ubicación",
  "localización",
  "geolocalización",
  "gps",
  "coordenadas",
  "mapa",
  "ubicación exacta",
  "dirección exacta",
  "calle",
  "número",
  "colonia",
  "barrio",
  "ciudad",
  "estado",
  "país",
  "código postal",
  "zip",
  "cp",
  "referencia",
  "punto de referencia",
  "lugar",
  "sitio",
  "punto de encuentro",
  "encuentro",
  "cita",
  "quedada",
  "reunión",
  "junta",
  "conocer",
  "conocerse",
  "verse",
  "vernos",
  "juntarse",
  "reunirse",
  "encontrarse",
  "encontrarnos",
  "ir a",
  "ir al",
  "ir a la",
  "ir a los",
  "ir a las",
  "visitar",
  "visita",
  "visitar a",
  "ir a casa",
  "ir a tu casa",
  "ir a mi casa",
  "ir a su casa",
  "en casa",
  "en tu casa",
  "en mi casa",
  "en su casa",
  "en tu lugar",
  "en mi lugar",
  "en su lugar",
  "en tu departamento",
  "en mi departamento",
  "en su departamento",
  "en tu apartamento",
  "en mi apartamento",
  "en su apartamento",
  "en tu cuarto",
  "en mi cuarto",
  "en su cuarto",
  "en tu habitación",
  "en mi habitación",
  "en su habitación",
  "en tu recámara",
  "en mi recámara",
  "en su recámara",
  "en tu cama",
  "en mi cama",
  "en su cama",
  "en tu coche",
  "en mi coche",
  "en su coche",
  "en tu auto",
  "en mi auto",
  "en su auto",
  "en tu carro",
  "en mi carro",
  "en su carro",
  "en tu vehículo",
  "en mi vehículo",
  "en su vehículo",
  "en tu camión",
  "en mi camión",
  "en su camión",
  "en tu camioneta",
  "en mi camioneta",
  "en su camioneta",
  "en tu van",
  "en mi van",
  "en su van",
  "en tu motel",
  "en mi motel",
  "en su motel",
  "en tu hotel",
  "en mi hotel",
  "en su hotel",
  "en tu casa de huéspedes",
  "en mi casa de huéspedes",
  "en su casa de huéspedes",
  "en tu airbnb",
  "en mi airbnb",
  "en su airbnb",
  "en tu departamento airbnb",
  "en mi departamento airbnb",
  "en su departamento airbnb",
  "en tu habitación airbnb",
  "en mi habitación airbnb",
  "en su habitación airbnb",
  "reservar",
  "reserva",
  "reservar habitación",
  "reservar cuarto",
  "reservar motel",
  "reservar hotel",
  "reservar casa",
  "reservar departamento",
  "reservar apartamento",
  "reservar lugar",
  "reservar sitio",
  "pagar",
  "pagar por",
  "pagar a",
  "cobrar",
  "cobrar por",
  "cobrar a",
  "costo",
  "precio",
  "tarifa",
  "cuota",
  "pago",
  "abono",
  "anticipo",
  "seña",
  "seña",
  "adelanto",
  "depósito",
  "garantía",
  "fianza",
  "seguro",
  "póliza",
  "contrato",
  "acuerdo",
  "convenio",
  "pacto",
  "trato",
  "negociación",
  "negociar",
  "acordar",
  "convenir",
  "pactar",
  "tratar",
  "negociado",
  "acordado",
  "convenido",
  "pactado",
  "tratado",
  // Palabras adicionales para mayor robustez
  "crack",
  "heroína",
  "metanfetamina",
  "éxtasis",
  "lsd",
  "ácido",
  "mushrooms",
  "hongos",
  "coca",
  "perico",
  "yerba",
  "mota",
  "maría",
  "juana",
  "pastillas",
  "pastilla",
  "drogado",
  "drogada",
  "narco",
  "narcotraficante",
  "camello",
  "mula",
  "sicariato",
  "ejecución",
  "ejecutar",
  "asesinato",
  "magnicidio",
  "genocidio",
  "limpieza étnica",
  "tortura",
  "torturar",
  "golpiza",
  "golpear",
  "patear",
  "puñetazo",
  "puñalada",
  "apuñalar",
  "disparar",
  "disparo",
  "balazo",
  "bala",
  "arma de fuego",
  "arma blanca",
  "explosivos",
  "bombas",
  "granada",
  "dinamita",
  "c4",
  "terrorista",
  "secuestrador",
  "secuestrada",
  "secuestrado",
  "cautiverio",
  "rehen",
  "rehén",
  "rehenes",
  "chantajista",
  "extorsionista",
  "estafador",
  "estafadora",
  "defraudador",
  "defraudadora",
  "timador",
  "timadora",
  "pirata",
  "piratería",
  "hackeo",
  "hackear",
  "intrusión",
  "intruso",
  "intrusa",
  "malware",
  "virus",
  "ransomware",
  "spyware",
  "adware",
  "troyano",
  "keylogger",
  "phishing",
  "smishing",
  "vishing",
  "spoofing",
  "identity theft",
  "robo de identidad",
  "suplantación",
  "clonación",
  "clonar",
  "falsificación",
  "falsificar",
  "documento falso",
  "identidad falsa",
  "pasaporte falso",
  "licencia falsa",
  "cédula falsa",
  "ine falso",
  "curp falso",
  "rfc falso",
  "acta falso",
  "certificado falso",
  "título falso",
  "diploma falso",
  "contrato falso",
  "recibo falso",
  "factura falsa",
  "comprobante falso",
  "pago falso",
  "transferencia falsa",
  "depósito falso",
  "retiro falso",
  "cheque falso",
  "tarjeta falsa",
  "tarjeta clonada",
  "tarjeta robada",
  "cuenta robada",
  "cuenta hackeada",
  "perfil falso",
  "perfil robado",
  "perfil hackeado",
  "cuenta falsa",
  "cuenta clonada",
  "bot",
  "botnet",
  "script",
  "automatización",
  "automatizado",
  "automatizada",
  "programa",
  "software",
  "aplicación",
  "app",
  "tool",
  "herramienta",
  "sistema",
  "plataforma",
  "servicio",
  "servicio premium",
  "premium",
  "vip",
  "gold",
  "platinum",
  "diamond",
  "elite",
  "exclusive",
  "exclusivo",
  "exclusiva",
  "limitado",
  "limitada",
  "oferta",
  "oferta especial",
  "oferta única",
  "oferta limitada",
  "promoción",
  "promoción especial",
  "promoción única",
  "promoción limitada",
  "descuento",
  "descuento especial",
  "descuento único",
  "descuento limitado",
  "rebaja",
  "rebaja especial",
  "rebaja única",
  "rebaja limitada",
  "oferta flash",
  "venta flash",
  "liquidación",
  "liquidación total",
  "liquidación parcial",
  "remate",
  "remate total",
  "remate parcial",
  "subasta",
  "subasta en línea",
  "subasta online",
  "puja",
  "ofertar",
  "ganar",
  "ganador",
  "ganadora",
  "premio",
  "premio mayor",
  "premio en efectivo",
  "premio en dinero",
  "premio en especie",
  "sorteo",
  "rifa",
  "lotería",
  "bingo",
  "casino",
  "casino online",
  "casino en línea",
  "apuestas",
  "apuestas deportivas",
  "apuestas en vivo",
  "apuestas online",
  "apuestas en línea",
  "trading",
  "forex",
  "binarias",
  "opciones binarias",
  "cripto",
  "criptomonedas",
  "bitcoin",
  "ethereum",
  "litecoin",
  "ripple",
  "dogecoin",
  "usdt",
  "usdc",
  "bnb",
  "solana",
  "cardano",
  "polkadot",
  "avalanche",
  "chainlink",
  "polygon",
  "shiba",
  "doge",
  "pepe",
  "meme",
  "meme coin",
  "token",
  "nft",
  "nfts",
  "web3",
  "blockchain",
  "defi",
  "dao",
  "metaverso",
  "metaverse",
  "play to earn",
  "p2e",
  "move to earn",
  "m2e",
  "learn to earn",
  "l2e",
  "watch to earn",
  "w2e",
  "click to earn",
  "c2e",
  "earn",
  "ganar",
  "ganar dinero",
  "ganar cripto",
  "ganar bitcoin",
  "ganar ethereum",
  "ganar tokens",
  "ganar nfts",
  "minar",
  "minar bitcoin",
  "minar cripto",
  "minar tokens",
  "minar nfts",
  "staking",
  "farm",
  "farming",
  "yield farming",
  "liquidity mining",
  "liquidity pool",
  "pool",
  "lp",
  "airdrop",
  "airdrops",
  "bounty",
  "bounties",
  "referral",
  "referido",
  "referidos",
  "afiliado",
  "afiliados",
  "programa de afiliados",
  "mlm",
  "multinivel",
  "network marketing",
  "mercadotecnia en red",
  "pirámide",
  "esquema piramidal",
  "ponzi",
  "esquema ponzi",
  "esquema de inversión",
  "inversión garantizada",
  "inversión segura",
  "inversión sin riesgo",
  "rendimiento garantizado",
  "rendimiento seguro",
  "rendimiento sin riesgo",
  "ganancia garantizada",
  "ganancia segura",
  "ganancia sin riesgo",
  "retorno garantizado",
  "retorno seguro",
  "retorno sin riesgo",
  "duplicar",
  "duplicar dinero",
  "duplicar inversión",
  "triplicar",
  "triplicar dinero",
  "triplicar inversión",
  "multiplicar",
  "multiplicar dinero",
  "multiplicar inversión",
  "crecer",
  "crecer dinero",
  "crecer inversión",
  "hacerse rico",
  "hacerse rica",
  "ser rico",
  "ser rica",
  "millonario",
  "millonaria",
  "libertad financiera",
  "independencia financiera",
  "retiro temprano",
  "retiro anticipado",
  "jubilación",
  "jubilación temprana",
  "jubilación anticipada",
  "fuego",
  "fuego colombiano",
  "retiro",
  "retiro financiero",
  "retiro temprano",
  "retiro anticipado",
  "plan de retiro",
  "fondo de retiro",
  "pensión",
  "pensión temprana",
  "pensión anticipada",
  "ahorro",
  "ahorrar",
  "inversión",
  "invertir",
  "dinero",
  "dinero extra",
  "ingreso extra",
  "ingresos extra",
  "dinero adicional",
  "ingresos adicionales",
  "dinero pasivo",
  "ingresos pasivos",
  "dinero residual",
  "ingresos residuales",
  "flujo de efectivo",
  "cashflow",
  "cash flow",
  "libertad",
  "libertad de tiempo",
  "libertad financiera",
  "libertad geográfica",
  "viajar",
  "viajes",
  "vacaciones",
  "lifestyle",
  "estilo de vida",
  "lujo",
  "vida de lujo",
  "exclusivo",
  "exclusiva",
  "premium",
  "vip",
  "élite",
  "clase alta",
  "alta sociedad",
  "riqueza",
  "abundancia",
  "prosperidad",
  "éxito",
  "exitoso",
  "exitosa",
  "triunfador",
  "triunfadora",
  "ganador",
  "ganadora",
  "líder",
  "líderes",
  "mentor",
  "mentores",
  "coach",
  "coaches",
  "gurú",
  "gurús",
  "experto",
  "expertos",
  "profesional",
  "profesionales",
  "maestro",
  "maestra",
  "instructor",
  "instructora",
  "entrenador",
  "entrenadora",
  "academia",
  "curso",
  "cursos",
  "clase",
  "clases",
  "taller",
  "talleres",
  "seminario",
  "seminarios",
  "webinar",
  "webinars",
  "masterclass",
  "masterclasses",
  "formación",
  "capacitación",
  "educación",
  "aprendizaje",
  "aprender",
  "certificado",
  "certificados",
  "diploma",
  "diplomas",
  "título",
  "títulos",
  "licencia",
  "licencias",
  "credencial",
  "credenciales",
  "acreditación",
  "acreditaciones",
  "certificación",
  "certificaciones",
  "validación",
  "validaciones",
  "verificación",
  "verificaciones",
  "aprobado",
  "aprobada",
  "oficial",
  "autorizado",
  "autorizada",
  "regulado",
  "regulada",
  "legal",
  "legítimo",
  "legítima",
  "seguro",
  "segura",
  "confiable",
  "confianza",
  "garantía",
  "garantizado",
  "garantizada",
  "asegurado",
  "asegurada",
  "protegido",
  "protegida",
  "seguridad",
  "protección",
  "privacidad",
  "datos personales",
  "información personal",
  "información confidencial",
  "datos confidenciales",
  "información sensible",
  "datos sensibles",
  "privado",
  "privada",
  "confidencial",
  "secreto",
  "secreta",
  "discreto",
  "discreta",
  "anónimo",
  "anónima",
  "anónimato",
  "sin rastro",
  "sin dejar rastro",
  "borrar rastros",
  "eliminar rastros",
  "ocultar",
  "ocultar identidad",
  "máscara",
  "disfraz",
  "falso",
  "falsa",
  "falsificación",
  "falsificar",
  "documento falso",
  "identidad falsa",
  "nombre falso",
  "alias",
  "seudónimo",
  "nick",
  "nickname",
  "usuario",
  "cuenta",
  "perfil",
  "biografía",
  "bio",
  "descripción",
  "descripción personal",
  "información de contacto",
  "contacto",
  "teléfono",
  "celular",
  "móvil",
  "whatsapp",
  "telegram",
  "instagram",
  "facebook",
  "twitter",
  "tiktok",
  "snapchat",
  "linkedin",
  "correo",
  "email",
  "gmail",
  "hotmail",
  "outlook",
  "yahoo",
  "dirección",
  "ubicación",
  "localización",
  "geolocalización",
  "gps",
  "coordenadas",
  "mapa",
  "ubicación exacta",
  "dirección exacta",
  "calle",
  "número",
  "colonia",
  "barrio",
  "ciudad",
  "estado",
  "país",
  "código postal",
  "zip",
  "cp",
  "referencia",
  "punto de referencia",
  "lugar",
  "sitio",
  "punto de encuentro",
  "encuentro",
  "cita",
  "quedada",
  "reunión",
  "junta",
  "conocer",
  "conocerse",
  "verse",
  "vernos",
  "juntarse",
  "reunirse",
  "encontrarse",
  "encontrarnos",
  "ir a",
  "ir al",
  "ir a la",
  "ir a los",
  "ir a las",
  "visitar",
  "visita",
  "visitar a",
  "ir a casa",
  "ir a tu casa",
  "ir a mi casa",
  "ir a su casa",
  "en casa",
  "en tu casa",
  "en mi casa",
  "en su casa",
  "en tu lugar",
  "en mi lugar",
  "en su lugar",
  "en tu departamento",
  "en mi departamento",
  "en su departamento",
  "en tu apartamento",
  "en mi apartamento",
  "en su apartamento",
  "en tu cuarto",
  "en mi cuarto",
  "en su cuarto",
  "en tu habitación",
  "en mi habitación",
  "en su habitación",
  "en tu recámara",
  "en mi recámara",
  "en su recámara",
  "en tu cama",
  "en mi cama",
  "en su cama",
  "en tu coche",
  "en mi coche",
  "en su coche",
  "en tu auto",
  "en mi auto",
  "en su auto",
  "en tu carro",
  "en mi carro",
  "en su carro",
  "en tu vehículo",
  "en mi vehículo",
  "en su vehículo",
  "en tu camión",
  "en mi camión",
  "en su camión",
  "en tu camioneta",
  "en mi camioneta",
  "en su camioneta",
  "en tu van",
  "en mi van",
  "en su van",
  "en tu motel",
  "en mi motel",
  "en su motel",
  "en tu hotel",
  "en mi hotel",
  "en su hotel",
  "en tu casa de huéspedes",
  "en mi casa de huéspedes",
  "en su casa de huéspedes",
  "en tu airbnb",
  "en mi airbnb",
  "en su airbnb",
  "en tu departamento airbnb",
  "en mi departamento airbnb",
  "en su departamento airbnb",
  "en tu habitación airbnb",
  "en mi habitación airbnb",
  "en su habitación airbnb",
  "reservar",
  "reserva",
  "reservar habitación",
  "reservar cuarto",
  "reservar motel",
  "reservar hotel",
  "reservar casa",
  "reservar departamento",
  "reservar apartamento",
  "reservar lugar",
  "reservar sitio",
  "pagar",
  "pagar por",
  "pagar a",
  "cobrar",
  "cobrar por",
  "cobrar a",
  "costo",
  "precio",
  "tarifa",
  "cuota",
  "pago",
  "abono",
  "anticipo",
  "seña",
  "adelanto",
  "depósito",
  "garantía",
  "fianza",
  "seguro",
  "póliza",
  "contrato",
  "acuerdo",
  "convenio",
  "pacto",
  "trato",
  "negociación",
  "negociar",
  "acordar",
  "convenir",
  "pactar",
  "tratar",
  "negociado",
  "acordado",
  "convenido",
  "pactado",
  "tratado",
]);
